name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Hola! @${{ github.actor }} 🥳, You just created an Issue!🌟 Thanks for the contribution."
        pr-message: "Submitted a PR already That's amazing @${{ github.actor }}. Sit tight, we will be reviewing it soon. Make sure you read the contributing guide."
